IMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.dashboard_index, name='dashboard_index'),
    path('add-products/', views.add_products, name='add_products'),
    path('search-products/', views.search_available_products, name='search_available_products'),
    path('view-available-products/', views.view_available_products, name='view_available_products'),
    path('sell-available-products/', views.sell_available_products, name='sell_available_products'),
    path('view-sold-products/', views.view_sold_products, name='view_sold_products'),
    path('users/', views.users, name='users'),
    path('users/all/',views.view_availableUsers,name='view_users'),
    path('users/<int:pk>/',views.userDetail,name='user_detail'),
]

dashboard/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Available_product_table(models.Model):
    product_name = models.CharField(max_length=50)
    product_price = models.IntegerField()
    product_quantity = models.IntegerField()
    added_by = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)


    def __str__(self):
        return f"{self.id} - {self.product_name} - {self.product_price} - {self.product_quantity} - {self.added_by}"


class Sold_product_table(models.Model):
    date_time = models.DateTimeField(auto_now=True)
    product_id = models.IntegerField()
    product_name = models.CharField(max_length=50)
    product_price = models.IntegerField()
    product_quantity = models.IntegerField()
    sold_by = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)

    def __str__(self):
        return f"{self.id} - {self.date_time} - {self.product_id} - {self.product_name} - {self.product_price} - {self.product_quantity}"


class Store(models.Model):
    name = models.CharField(max_length=250)
    owner = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)

    class Meta:
        unique_together = ["name","owner"]

dashboard/forms.py
from django import forms
from .models import Available_product_table

class AddProductForm(forms.ModelForm):
    product_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Product Name'}))
    product_price = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Product Price'}))
    product_quantity = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Quantity'}))
    
    class Meta():
        model = Available_product_table
        fields = ['product_name','product_price','product_quantity']


class SearchForm(forms.Form):
    search_product = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Product Name','class':'form-control my-0 py-1'}))

dashboard/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
from .forms import AddProductForm, SearchForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .auth import admin_only
from django.contrib.auth.models import User
from django.db.models import Q
from django.core import mail

connection = mail.get_connection()

connection.open()


@login_required
def dashboard_index(request):   
    shop_name = request.user.username
    shop_name = shop_name.split("_")
    shop_name = map(lambda x: x.capitalize(),shop_name)
    shop_name = ' '.join(shop_name)

    return render(request,'dashboard/index.html',context={'title':'Dashboard',"shop":str(shop_name),"user": request.user})



#add_products
@login_required
def add_products(request):
    form = AddProductForm()

    if request.method == 'POST':
        form = AddProductForm(request.POST)
        user = request.user
        
        if form.is_valid():
            created = models.Available_product_table.objects.create(added_by=request.user,**form.cleaned_data)
            # form.save()
            
            context = {
                'result' : 'New Product Added successfully',
                'title':'Add Products',
            }
            return render(request,'dashboard/result.html',context=context)

        else:
            context = {
                'result' : 'ERROR',
                'title':'Add Products',
            }
            return render(request,'dashboard/result.html',context=context)

    context = {
        'form' : form,
        'title':'Add Products',
        }

    return render(request,'dashboard/add_product.html',context=context)





# search_available_products
@login_required
def search_available_products(request):
    form = SearchForm()

    if request.method == 'POST':
        form = SearchForm(request.POST)
        
        if form.is_valid():
            search_product = form.cleaned_data['search_product']
            
            all_products = models.Available_product_table.objects.filter(product_name__contains = search_product).values()  
            #print(all_products)
            context = {
                'all_products' : all_products,
                'title' : 'Search Result',
            }
            
            return render(request,'dashboard/view_available_products.html',context=context)


    context = {
        'form' : form,
        'title':'Search Products',
        }

    return render(request,'dashboard/search_product.html',context=context)


# view_available_products 
@login_required
def view_available_products(request):
    
    all_products = models.Available_product_table.objects.all()
    
    context = {
        'all_products' : all_products,
        'title' : 'All Products',
        }
        
    return render(request,'dashboard/view_available_products.html',context=context)

from datetime import datetime
# from django.utils.timezone import get_current_timezone
@admin_only
@login_required
def view_availableUsers(request):
    all_users = User.objects.only("id","username","date_joined").filter(~Q(is_superuser=1))
    
    for user in all_users:
        shop_name = user.username
        shop_name = shop_name.split("_")
        shop_name = map(lambda x: x.capitalize(),shop_name)
        shop_name = ' '.join(shop_name)
        # tz = get_current_timezone()
        dt = user.date_joined.strftime('%m/%d/%Y')
        user.shop_name  = shop_name
        user.date_joined = dt
    print(all_users)
    context = {
        "users" : all_users
    }

    return render(request,"dashboard/view_available_shops.html",context= context)


@login_required
def userDetail(request,pk):
    user_detail = User.objects.get(id=pk)
    shop_name = user_detail.username
    shop_name = shop_name.split("_")
    shop_name = map(lambda x: x.capitalize(),shop_name)
    shop_name = ' '.join(shop_name)

    listed_products = models.Available_product_table.objects.filter(added_by=pk)
    sold_products = models.Sold_product_table.objects.filter(sold_by=pk)
    context = {
        "shop": shop_name,
        "listings": listed_products,
        "sold": sold_products
    }
    return render(request,"dashboard/user_detail.html",context= context)


# sell_available_products
@login_required
def sell_available_products(request):

    if request.method == 'POST':
        sell_product_id = request.POST['product_id']
        sell_qty = int(request.POST['sellqty'])
        
        sell_product = models.Available_product_table.objects.filter(id = sell_product_id).values()
        sell_product = sell_product[0]

        if  sell_qty <= sell_product['product_quantity']:
            user = request.user
            product = models.Sold_product_table(
                product_id = sell_product['id'], 
                product_name = sell_product['product_name'],
                product_price = sell_product['product_price'],
                product_quantity = sell_qty,
                sold_by = user
            )
            product.save()

            # UPDATE Available_product_table
            remaning_qty = sell_product['product_quantity'] - sell_qty

            update_product = models.Available_product_table.objects.get(id = sell_product_id)
            update_product.product_quantity = remaning_qty
            update_product.save()
            total_price = sell_qty * int(sell_product['product_price'])
            
            subject = str(sell_qty) + " of "+ sell_product['product_name'] + " Sold"
            body =  f'''
                    {sell_product['product_name']} was sold by  {user.username},
                    {total_price} accumulated from {str(sell_qty)} of products
                    '''

            email = mail.EmailMessage(subject.title(), body.capitalize(), to=['kadeceh288@fsouda.com'])

            email.send()
            
            context = {
                'result' : 'Product sold successfully!',
                'title':'Sell Products',
            }
            return render(request,'dashboard/result.html',context=context)

        else:
            context = {
                'result' : 'Enter Quantity is less than available stock or Product is Out of Stock!',
                'title':'Sell Products',
            }
            return render(request,'dashboard/result.html',context=context)
        
    if request.user.is_superuser:
        all_products = models.Available_product_table.objects.all()
        context = {
            'all_products' : all_products,
            'title' : 'Sell Products',
            }
                
        return render(request,'dashboard/sell_products.html',context=context)
    else:
        all_products = models.Available_product_table.objects.filter(added_by=request.user)
        context = {
            'all_products' : all_products,
            'title' : 'Sell Products',
            }
                
        return render(request,'dashboard/sell_products.html',context=context)





# view_sold_products
@login_required
def view_sold_products(request):
    
    all_sold_products = models.Sold_product_table.objects.all()
    context = {
        'all_sold_products' : all_sold_products,
        'title' : 'Sold Products',
        }
            
    return render(request,'dashboard/view_sold_products.html',context=context)
    
       





@admin_only
@login_required
def users(request):
    form = UserCreationForm

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        print(form)
        
        if form.is_valid():
            form.save()
            
            context = {
                'result' : 'User Added successfully',
                'title':'Add User',
            }
            return render(request,'dashboard/result.html',context=context)

        else:
            context = {
                'result' : 'ERROR - Does not meet the requirements!',
                'title':'Add User',
            }
            return render(request,'dashboard/result.html',context=context)

    context = {
        'form' : form,
        'title':'Add User',
        }

    return render(request,'dashboard/user.html',context=context)

dashboard/templates/dashboard/add_product.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <form method="POST">
        {% csrf_token %}

        <div class="form-group mx-4 mt-4">
            {{form.as_p}} 
        </div>
        
        <div class="form-group mx-4 mt-4">
            <button type="submit" class="btn login-btn btn-block ">Add Product</button>
        </div>
    </form>

        
{% endblock %}

dashboard/templates/dashboard/base.html
{% extends 'base.html' %}
{% block content %}

    <div class="container h-100">
        <div class="row align-items-center h-100" >
            
            <div class="col-9 mx-auto">
                <div class="mt-4">
                    <div class="text-center p-1">
                        <h3 class="theme-color">{{title}}</h3>
                    </div>
                </div>

                {% block dashboardcontent %}

                {% endblock %}

            </div>
        </div>
    </div>


{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% block content %}

  <div class="mt-4">
    {% if not user.is_superuser %}
      <div class="text-center p-3">
          <h2 class="theme-color">{{shop}} Shop</h2>
      </div>
    {% endif %}
    <div class="text-center p-3">
        <h2 class="theme-color">Dashboard</h2>
    </div>
  </div>

  {% if user.is_superuser %}
  <div class="container pb-3">
    <div class="d-flex justify-content-center align-items-center">
      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:view_users' %}'">
          <i class="fa fa-list pr-3"></i> View Users
        </button>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="container">

    {% if user.is_superuser %}
    <div class="row my-4">
      
      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:add_products' %}'">
          <i class="far fa-plus-square pr-3"></i> Add Products
        </button>
      </div>

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:sell_available_products' %}'">
          <i class="far fa-minus-square pr-3"></i> Sell Products
        </button>
      </div>

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:users' %}'">
          <i class="fas fa-user-shield pr-3"></i> Add Users
        </button>
      </div>

    </div>
    {% endif %}


    <div class="row my-4">
      
      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:search_available_products' %}'">
          <i class="fas fa-search pr-3"></i> Search Products
        </button>
      </div>

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:view_sold_products' %}'">
          <i class="fas fa-boxes pr-3"></i> View Sold Products
        </button>
      </div>

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:view_available_products' %}'">
          <i class="fas fa-boxes pr-3"></i> View Available Products
        </button>
      </div>


    </div>
  </div>
      

{% endblock  %}

dashboard/templates/dashboard/result.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

<h3 class='text-center m-4'>{{result}}</h3>

<button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>
        
{% endblock %}

dashboard/templates/dashboard/search_product.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <form method="POST">
        <div class="input-group md-form form-md form-2 p-3">
            {{form.search_product}}
            {% csrf_token %}
           
            <button class="btn my-0 py-1" type="submit">
                <span class="input-group-text search-btn" id="basic-text1">
                    <i class="fas fa-search fa-fw search-icon" aria-hidden="true"></i>
                </span>
            </button>
        
        </div>
    </form>

{% endblock %}

dashboard/templates/dashboard/sell_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group mx-4 mt-4">
            <select name='product_id' class="form-control" required>
                <option value="" disabled selected hidden>-- Select Product --</option>
                {% if all_products.count > 0 %}

                    {% for item in all_products %}
                        <option value={{item.id}}>Product id: {{item.id}}  - {{item.product_name}}</option>
                    {% endfor %}

                {% endif %}
            </select>
        </div>
        
        <div class="form-group mx-4 mt-4">
            <input type="number" required name="sellqty" class="form-control" placeholder="Quantity" min="1">
        </div>

        <div class="form-group mx-4 mt-4">
            <button type="submit" class="btn login-btn btn-block ">Sell Product</button>
        </div>
    </form>

{% endblock %}

dashboard/templates/dashboard/test.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

TEST HTML DATA

{% endblock %}

dashboard/templates/dashboard/user.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <form method="POST">
        {% csrf_token %}

        <div class="form-group mx-4 mt-4">
            {{form.username.label_tag}}
            <input type="text" required name="username" class="form-control" placeholder="Enter Username">
        </div>

        <div class="form-group mx-4 mt-4">
            {{form.password1.label_tag}}
            <input type="password" required  name="password1" class="form-control" placeholder="Enter Password">
        </div>

        <div class="form-group mx-4 mt-4">
            {{form.password2.label_tag}}
            <input type="password" required  name="password2" class="form-control" placeholder="Enter the same password as before, for verification.">
        </div>
        
        <div class="form-group mx-4 mt-4">
            <button type="submit" class="btn login-btn btn-block ">Add User</button>
        </div>
       
    </form>

{% endblock %}

dashboard/templates/dashboard/user_detail.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}
    <div class="container m-3 p-2">
        <div class="text-center">
            <h4 class="h4">
                Shop Activity of {{ shop }} 
            </h3>
        </div>
    </div>

    <div class="container mt-3">
        <div class="text-center">
            <h4 class="h4">
                Products listed 
            </h3>
        </div>
    </div>

    {% if listings.count > 0 %}
    
        <table class='table table-striped'>
            <thead>
                <tr>
                    <th scope='col'>Product ID</th>
                    <th scope='col'>Product Name</th>
                    <th scope='col'>Product Price</th>
                    <th scope='col'>Quantity</th>
                </tr>
            </thead>
            
            <tbody>
                {% for item in all_products %}
                    <tr>
                        <td scope='row'>{{item.id}}</th>
                        <td scope='row'>{{item.product_name}}</td>
                        <td scope='row'>{{item.product_price}}</td>
                        <td scope='row'>{{item.product_quantity}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
        <h1 class='text-center'>No Products are thier to view....</h1>

    {% endif %}

    <div class="container mt-3">
        <div class="text-center">
            <h3>
                Products Sold 
            </h3>
        </div>
    </div>

    {% if sold.count > 0 %}


        <table class='table table-striped'>
            <thead>
                <tr>
                    <th scope='col'>Date Time</th>
                    <th scope='col'>Product ID</th>
                    <th scope='col'>Product Name</th>
                    <th scope='col'>Product Price</th>
                    <th scope='col'>Quantity</th>
                    <th scope='col'>Sold By</th>
                </tr>
            </thead>
            
            <tbody>
                {% for item in all_sold_products %}
                    <tr>
                        <td scope='row'>{{item.date_time}}</th>
                        <td scope='row'>{{item.product_id}}</th>
                        <td scope='row'>{{item.product_name}}</td>
                        <td scope='row'>{{item.product_price}}</td>
                        <td scope='row'>{{item.product_quantity}}</td>
                        <td scope='row'>{{item.sold_by.username}}</td>
                    </tr>

                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
        <h1 class='text-center'>No Products are thier to view....</h1>

    {% endif %}
    
    <button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>          


{% endblock %}

dashboard/templates/dashboard/view_available_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    {% if all_products.count > 0 %}

        <table class='table table-striped'>
            <thead>
                <tr>
                    <th scope='col'>Product ID</th>
                    <th scope='col'>Product Name</th>
                    <th scope='col'>Product Price</th>
                    <th scope='col'>Quantity</th>
                </tr>
            </thead>
            
            <tbody>
                {% for item in all_products %}
                    <tr>
                        <td scope='row'>{{item.id}}</th>
                        <td scope='row'>{{item.product_name}}</td>
                        <td scope='row'>{{item.product_price}}</td>
                        <td scope='row'>{{item.product_quantity}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
        <h1 class='text-center'>No Products are thier to view....</h1>

    {% endif %}
    
    <button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>          


{% endblock %}

dashboard/templates/dashboard/view_available_shops.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    {% if users.count > 0 %}

        <table class='table table-striped'>
            <thead>
                <tr>
                    <th scope='col'>id</th>
                    <th scope='col'>User</th>
                    <th scope='col'>Shop Name</th>
                    <th scope='col'>Date Joined</th>
                    <th scope="col">#</th>
                </tr>
            </thead>
            
            <tbody>
                {% for item in users %}
                    <tr>
                        <td scope='row'>{{item.id}}</th>
                        <td scope='row'>{{item.username}}</td>
                        <td scope='row'>{{item.shop_name}}</td>
                        <td scope='row'>{{item.date_joined}}</td>
                        <td scope='row'><a class="btn btn-primary action-btn btn-block" href="{% url 'dashboard:user_detail' pk=item.id %}">View</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
        <h1 class='text-center'>No Users with Shops to view....</h1>

    {% endif %}
    
    <button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>          


{% endblock %}

dashboard/templates/dashboard/view_sold_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    {% if all_sold_products.count > 0 %}

        <table class='table table-striped'>
            <thead>
                <tr>
                    <th scope='col'>Date Time</th>
                    <th scope='col'>Product ID</th>
                    <th scope='col'>Product Name</th>
                    <th scope='col'>Product Price</th>
                    <th scope='col'>Quantity</th>
                    <th scope='col'>Sold By</th>
                </tr>
            </thead>
            
            <tbody>
                {% for item in all_sold_products %}
                    <tr>
                        <td scope='row'>{{item.date_time}}</th>
                        <td scope='row'>{{item.product_id}}</th>
                        <td scope='row'>{{item.product_name}}</td>
                        <td scope='row'>{{item.product_price}}</td>
                        <td scope='row'>{{item.product_quantity}}</td>
                        <td scope='row'>{{item.sold_by.username}}</td>
                    </tr>

                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
        <h1 class='text-center'>No Products are thier to view....</h1>

    {% endif %}
    
    <button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>          


{% endblock %}